// AUTO-GENERATED by scripts/gen-building-manifest.mjs — do not edit by hand.
// Lists, per building type, the ages for which a 'romans' sprite exists.

import type { Age, BuildingType } from '@shared/types';

export const BUILDING_IMAGE_AGES: Partial<Record<BuildingType, Age[]>> = {
  barracks: ['medieval', 'digital'],
  farm: ['stone', 'medieval'],
  goldMine: ['medieval'],
  house: ['stone', 'classical', 'medieval', 'industrial', 'digital'],
  market: ['medieval'],
  storage: ['medieval'],
  temple: ['medieval'],
  tower: ['medieval'],
  townCenter: ['stone', 'bronze', 'iron', 'classical', 'medieval', 'gunpowder', 'enlightenment', 'industrial', 'modern', 'digital'],
  wall: ['medieval'],
};
